<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\SingleFilePublish.props" />
  <Import Project="..\CliTool.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Rxdk.SkinBld</RootNamespace>
    <AssemblyName>skinbld</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="UixSchema.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rxdk.Bundler\Rxdk.Bundler.csproj" />
  </ItemGroup>
</Project>
