<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Project="$(MSBuildThisFileDirectory)ImportBefore\*.props" Condition="Exists('$(MSBuildThisFileDirectory)ImportBefore')" />

    <PropertyGroup>
        <EnableStdModules>false</EnableStdModules>
        <IncludePath>$(RXDK)\sdk\include</IncludePath>
        <LibraryPath Condition="'$(UseDebugLibraries)' == 'true'">$(RXDK)\sdk\lib\debug</LibraryPath>
        <LibraryPath Condition="'$(UseDebugLibraries)' != 'true'">$(RXDK)\sdk\lib\release</LibraryPath>
        <IntellisenseIncludePath>$(RXDK)\sdk\intellisense</IntellisenseIncludePath>
    </PropertyGroup>

    <!-- Specific values -->
    <PropertyGroup Condition="'$(ConfigurationType)' == 'Application'">
        <LinkCompiled>true</LinkCompiled>
        <TargetExt>.xbe</TargetExt>
        <OutputType>exe</OutputType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(ConfigurationType)' == 'DebuggerExtension'">
        <LibCompiled>true</LibCompiled>
        <TargetExt>.dxt</TargetExt>
        <OutputType>library</OutputType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(ConfigurationType)' == 'StaticLibrary'">
        <LibCompiled>true</LibCompiled>
        <TargetExt>.lib</TargetExt>
        <OutputType>staticlibrary</OutputType>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <ClCompile>
            <WarningLevel>EnableAllWarnings</WarningLevel>
            <DebugInfo Condition="'$(UseDebugLibraries)' == 'true'">FullDebug</DebugInfo>
            <DebugInfo Condition="'$(UseDebugLibraries)' != 'true'">LineNumber</DebugInfo>
            <PreprocessorDefinitions Condition="'$(UseDebugLibraries)' != 'true'">NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
            <Optimization Condition="'$(UseDebugLibraries)' == 'true'">None</Optimization>
            <Optimization Condition="'$(UseDebugLibraries)' != 'true'">Full</Optimization>
            <ProgramDatabaseFileName Condition="'$(ConfigurationType)' != 'StaticLibrary'">$(IntDir)</ProgramDatabaseFileName>
            <ProgramDatabaseFileName Condition="'$(ConfigurationType)' == 'StaticLibrary'">$(OutDir)</ProgramDatabaseFileName>
            <OmitFramePointers Condition="'$(UseDebugLibraries)' == 'true'">false</OmitFramePointers>
            <OmitFramePointers Condition="'$(UseDebugLibraries)' != 'true'">true</OmitFramePointers>
            <ExceptionHandling>Enabled</ExceptionHandling>
            <FunctionLevelLinking Condition="'$(UseDebugLibraries)' == 'true'">false</FunctionLevelLinking>
            <FunctionLevelLinking Condition="'$(UseDebugLibraries)' != 'true'">true</FunctionLevelLinking>
            <DataLevelLinking Condition="'$(UseDebugLibraries)' == 'true'">false</DataLevelLinking>
            <DataLevelLinking Condition="'$(UseDebugLibraries)' != 'true'">true</DataLevelLinking>
            <BufferSecurityCheck>true</BufferSecurityCheck>
            <PositionIndependentCode>false</PositionIndependentCode>
            <UseShortEnums>false</UseShortEnums>
            <RuntimeTypeInfo>false</RuntimeTypeInfo>
            <CLanguageStandard>c23</CLanguageStandard>
            <CppLanguageStandard>c++23</CppLanguageStandard>
            <PrecompiledHeader>NotUsing</PrecompiledHeader>
            <ObjectFileName>$(IntDir)%(filename).obj</ObjectFileName>
            <CompileAs>Default</CompileAs>
            <TreatWarningAsError>false</TreatWarningAsError>
            <Verbose>false</Verbose>
            <EnablePREfast Condition="'%(ClCompile.EnablePREfast)' == ''">false</EnablePREfast>
            <OmitFramePointers Condition="'%(ClCompile.OmitFramePointers)' == ''">false</OmitFramePointers>
            <MinimalRebuildFromTracking>true</MinimalRebuildFromTracking>
            <PrecompiledHeaderOutputFileDirectory>$(IntDir)</PrecompiledHeaderOutputFileDirectory>
            <PrecompiledHeaderOutputFile></PrecompiledHeaderOutputFile>
            <PrecompiledHeaderCompileAs>CompileAsCpp</PrecompiledHeaderCompileAs>
        </ClCompile>

        <Link>
            <EntryPointSymbol Condition="'$(ConfigurationType)' == 'Application'">XapiTitleStartup</EntryPointSymbol>
            <EntryPointSymbol Condition="'$(ConfigurationType)' == 'DebuggerExtension'">DxtEntry</EntryPointSymbol>
            <LibraryDependencies>libd3d8;libd3dx8;libxapi;libc;libcpp;libkernel</LibraryDependencies>
            <AdditionalDependencies />
            <AdditionalOptions>-rtlib=compiler-rt -Wl,--whole-archive -llibcompat -Wl,--no-whole-archive</AdditionalOptions>
        </Link>
    </ItemDefinitionGroup>

    <Import Project="$(MSBuildThisFileDirectory)ImportAfter\*.props" Condition="Exists('$(MSBuildThisFileDirectory)ImportAfter')" />
</Project>
